### ISSUE TITLE
API endpoints should always be ordered and filtered correctly

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/core#10]
All `index` API endpoints should order the results as expected (by default). This also needs to account for filtering for example, hidden component groups.

**Comment by joelbutcher** [comment]
@jbrooksuk what is the desired default ordering for these endpoints, by ID or by created_at date (should be identical)?

**Comment by jbrooksuk** [comment]
@joelbutcher IMHO, we should order incidents and metric points from newest to oldest. Everything else should be ascending by ID?

**Comment by joelbutcher** [comment]
@jbrooksuk it seems all these endpoints are already ordering things correctly. Have added some tests in my branch. What default filters need setting? As far as I can tell, this API is pretty solid already – great job!

**Comment by jbrooksuk** [comment]
@joelbutcher even for incidents and metrics in newest to oldest?

We should also make sure that you can filter correctly too.
