### ISSUE TITLE
General Error returned when running Migrations on 3.x with Sqlite

### ISSUE THREAD

**Issue by dakotawashok** [cachethq/core#120]
I think this error is because the migration didn't specify that this field can be nullable. Altering the line to `$table->json('payload')->nullable()->after('locked');` allows the migrations to run successfully.

https://github.com/cachethq/core/blob/9372410620c76108a77813ba40b24e509dd9fa87/database/migrations/2024_01_22_202432_update_settings_table.php#L17

```
 2023_08_30_212242_make_incident_updates_columns_nullable ............................................................................ 42.45ms DONE
  2023_08_30_212242_make_metrics_columns_nullable ..................................................................................... 51.24ms DONE
  2023_09_18_105838_add_engine_column_to_incident_templates_table ...................................................................... 8.65ms DONE
  2024_01_22_202432_update_settings_table ............................................................................................. 18.04ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (Connection: sqlite, SQL: alter table "settings" add column "payload" text not null)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

      +36 vendor frames 

  37  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))

➜  status_page git:(main) ✗
```

**Comment by jbrooksuk** [comment]
What database service are you using?

**Comment by dakotawashok** [comment]
Sorry, I'm not entirely sure. I believe it's just Sqlite with a `database/database.sqlite` file.

**Comment by jbrooksuk** [comment]
This migration is based off the `spatie/laravel-settings` migration — Cachet 3.x will migrate 2.x settings to the new format. https://github.com/spatie/laravel-settings/blob/main/database/migrations/create_settings_table.php.stub#L17

They don't have a `nullable` json field either... I wonder why that's failing for you. It doesn't happen when I run `composer start`...

**Comment by jbrooksuk** [comment]
@dakotawashok are you migrating a 2.x instance of Cachet or starting fresh?

**Comment by dakotawashok** [comment]
@jbrooksuk This is a new, fresh project using the 3.x branch as a base. 
Are you using sqlite when you run `composer start` to run the migrations, or another type of DB?
In fact, I'm not able to run `composer start` at all, it gives me this error: 
![image](https://github.com/user-attachments/assets/3821d12d-41bf-4703-a852-1756993405ae)

**Comment by jbrooksuk** [comment]
@dakotawashok just to check, are you cloning the Core repository or Cachet? The `start` and `dev` commands are definitely there, https://github.com/cachethq/core/blob/5557a4124a8a060b01c587fe58b012c3484b371b/composer.json#L72-L79.

**Comment by dakotawashok** [comment]
@jbrooksuk I think I'm cloning the [cachethq/cachet@3.x](https://github.com/cachethq/cachet/tree/3.x) branch, is that not the right way to install? https://github.com/cachethq/cachet/blob/a3ca218f97c252276ba46a61d775e3122254431c/composer.json#L47

**Comment by jbrooksuk** [comment]
@dakotawashok yeah, cloning the `3.x` branch is correct. Would you be open to emailing me, james [at] cachethq [dot] io and perhaps we could have a call to figure this out? I think it'd be easier!

**Comment by dakotawashok** [comment]
@jbrooksuk Absolutely, I'd be happy to!

**Comment by jbrooksuk** [comment]
Great! I look forward to it 😄

**Comment by dakotawashok** [comment]
I sent an email, lemme know if you got it 👍🏻

**Comment by jbrooksuk** [comment]
I didn't, sorry! Try james@alt-three.com instead please :)

**Comment by dakotawashok** [comment]
I sent an email to that one as well, but didn't get a response. I'm going to try again, but feel free to send me a message as well @jbrooksuk

**Comment by jbrooksuk** [comment]
@dakotawashok weird, I've not received any emails r.e. Cachet. Can you try sending to my alt-three.com again please?

**Comment by dakotawashok** [comment]
🫡 It's sent! Let me know if you get this one: 
![image](https://github.com/user-attachments/assets/5cf0940e-ffdc-468c-9cae-69bd7f0e3b0b)

**Comment by dakotawashok** [comment]
Also, we're getting this error when using regular `pgsql` as well, not just sqlite. We can go over how we install it/deploy it in email/chatting.

**Comment by dakotawashok** [comment]
I'm getting a successful migration with our project with the composer dependencies updated _and_ our project with the same old composer dependencies, so I'm not sure what happened or what changed in our setup. I'm going to do some more testing and I'll let you know how it goes. I saw the updated migrations test in that PR and I'm at least happy this all might've spurred that awesome testing setup :)

**Comment by jbrooksuk** [comment]
Awesome! Let me know if you run into any problems and we will jump on that call.

**Comment by dakotawashok** [comment]
@jbrooksuk I think I'm getting a related or the same error again, and I'm not sure why. This time, it's in the `2023_08_23_210836_make_incident_components_table_status_id_column_null.php` file. I was able to fix it, locally at least, by making the following change: ```
public function up(): void
    {
        Schema::table('incident_components', function (Blueprint $table) {
            $table->unsignedInteger('status_id')->nullable()->change();
        });
        Schema::table('incident_components', function (Blueprint $table) {
            $table->renameColumn('status_id', 'status');
        });
    }
```

**Comment by jbrooksuk** [comment]
@dakotawashok what version of SQLite are you using? I'm not seeing any issues when running this locally (in development) or deploying to Laravel Cloud (which I've configured to also use SQLite).

**Comment by dakotawashok** [comment]
@jbrooksuk this is actually with postgres now. Let me get a list of commands to reproduce this issue...

**Comment by jbrooksuk** [comment]
@dakotawashok oh right, that's also weird since we run the test suite on Postgres too with no issues.
