### ISSUE TITLE
Inconsistent padding on mobile header

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/core#145]
The header has too much horizontal padding on mobile. 

![image](https://github.com/user-attachments/assets/e58116a3-6c3f-4d8f-8df0-caf4acf4616c)

**Comment by ShaungBhone** [comment]
![Screenshot 2567-12-21 at 19 47 30](https://github.com/user-attachments/assets/bd79f3a1-f69b-489a-8041-c6d625a96163)
Everything is looking good to me.

**Comment by jbrooksuk** [comment]
Fixed by https://github.com/cachethq/core/pull/146
