### ISSUE TITLE
Error with npm run build

### ISSUE THREAD

**Issue by bezibaerchen** [cachethq/core#60]
npm run build fails.

Logs:

` npm run build

 build
 vite build

vite v3.2.7 building for production...
transforming (1) resources/js/cachet.jsBrowserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
✓ 7 modules transformed.
[vite:css] [postcss] ENOENT: no such file or directory, stat '/vendor/filament/filament/resources/css/theme.css'
file: /spare/download/core/resources/css/dashboard/theme.css:undefined:undefined
error during build:
Error: [postcss] ENOENT: no such file or directory, stat '/vendor/filament/filament/resources/css/theme.css'`

**Comment by jbrooksuk** [comment]
You need to run `composer install` first, to allow those dependencies to be created.
