### ISSUE TITLE
Help to deploy and test

### ISSUE THREAD

**Issue by Pingoo31** [cachethq/core#61]
Hi,
I tried to deploy the application in a container prepared for Laravel applications in order to test and see the evolution of the product but without prior knowledge of Laravel, none of my attempts worked :-(
Notably, as there is no "index.php" file in the "public" folder, I am not sure how to deploy such a project.

In the absence of installation documentation, could you help me on the steps to follow to launch this application?

Thanks in advance

**Comment by jbrooksuk** [comment]
@Pingoo31 sure, this package is a little confusing and although it's designed to be installed into existing Laravel applications, our advice is always to run Cachet as a standalone application. However, who am I to stop you? 😄 

**Steps:**

1. Install `cachethq/core` as a dependency - you'll need to use the dev version.
2. Publish the Cachet config files. Set `CACHET_PATH` in your `.env` to `CACHET_PATH=/status` or something other than `/`.
3. Make sure you run Cachet's migrations (there's a possibility of clashing migrations within existing applications).

Alternatively, take a look at https://github.com/cachethq/cachet/tree/3.x
