### ISSUE TITLE
Status Page Spacing

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/core#67]
Spacing between some status page elements is currently broken.

![CleanShot 2024-10-03 at 11 43 53@2x](https://github.com/user-attachments/assets/0c33d036-176e-4e30-bc05-b2304d91e892)

**Comment by ash-jc-allen** [comment]
Hey @jbrooksuk! Daft question, but has this been fixed? I've just had a look at this locally and it _appears_ to be spaced out nicely. But I'm not sure if I'm looking in the wrong place (apologies if so). I'm on the `main` branch, for reference 🙂

This is what I've got locally:
<img width="2532" alt="Screenshot 2024-10-04 at 17 16 35" src="https://github.com/user-attachments/assets/249e99d6-2b79-47a2-90b1-4053cc02c25a">

**Comment by jbrooksuk** [comment]
Yeah 😅 I had published the views and modified them by mistake.

**Comment by ash-jc-allen** [comment]
Easy mistake to make haha! 😁
