### ISSUE TITLE
Timeline "Today" Link

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/core#69]
The status page timeline component should display a pagination link for "Today" that jumps you back to the status page. This link should only be available when between pages.

![image](https://github.com/user-attachments/assets/3bb48411-2f72-4f6f-a6a6-8b7606204b87)

**Comment by steffjenl** [comment]
Start page:
![image](https://github.com/user-attachments/assets/9f63f373-0f57-44e8-a70d-8559d57051d0)

When page can be forwared:
![image](https://github.com/user-attachments/assets/750d0d98-75d9-4077-aee4-acfe561ef981)

**Comment by jbrooksuk** [comment]
Closed by https://github.com/cachethq/core/pull/108
