### ISSUE TITLE
Single Incident View Improvements

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/core#70]
Couple of improvements to the incident view page.

- [x] When viewing a single incident at `/incidents/{incident}` the page doesn't need the "About" section.
- [x] If an incident is linked to any components, we should display them here.

**Comment by RahatAhmed171** [comment]
Hi, how do i get startee contributing to this issue. Wanna give it a try

**Comment by jbrooksuk** [comment]
@RahatAhmed171 clone down the `cachethq/core` repository. Run `composer install` and `npm install`. Now run `npm run dev` and in a new terminal run `composer start`. That should do it!

**Comment by RahatAhmed171** [comment]
![error](https://github.com/user-attachments/assets/79ce69ba-e078-4e19-83c8-2e6545596c3d)
Dashboard doesnt show up. It returns 404 not found

**Comment by jbrooksuk** [comment]
https://x.com/jbrooksuk/status/1845087763835633898?s=46

Hope this helps!

**Comment by RahatAhmed171** [comment]
The dashboard link at the top doesn’t work at all. I inspected the href, the url looks like this:
```
<a href="/\dashboard" class="text-sm font-medium text-zinc-800 transition hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-300 sm:text-base">Dashboard</a>

```

**Comment by jbrooksuk** [comment]
How are you running Cachet? What's `CACHET_PATH` set to? I can't recreate this locally or at v3.cachethq.io

**Comment by RahatAhmed171** [comment]
so there is a dashboard function in src/cachet.php. I made some changes and and its working now (weird).
Regarding the single incident page, correct me if i am wrong, you want to display the component that is attached to a incident?
![single_incident](https://github.com/user-attachments/assets/ee6ffe4c-59fb-49ab-a305-b9cd1e27b7a0)
How do you want to display it? below the incident updates?

**Comment by jbrooksuk** [comment]
I'm glad you're sorted!

Well, we currently show an unstyled list of components when an incident is attached to one or more. I think we should firstly improve that UI (in the timeline) and then figure out a way that can be improved in this view.

**Comment by RahatAhmed171** [comment]
That makes sense.  Do you have any specific ideas on what changes would make the component list look more user-friendly?

**Comment by jbrooksuk** [comment]
The design by Jump24 actually had it quite similar to what we have:
![CleanShot 2024-10-16 at 13 15 25@2x](https://github.com/user-attachments/assets/86a97d9c-da1f-402c-8b84-619b2fa10d52)

**Comment by RahatAhmed171** [comment]
This is only one component above the incident title . If there's more than one component it shows as comma-separated list

**Comment by jbrooksuk** [comment]
Yeah, I think so.

Also, we could take this a step further... what if instead of making them a string, they were a block of individual Blade components that had the status icon and a tooltip or something for interactivity?

**Comment by jbrooksuk** [comment]
I checked the single incident page and this is all done now.
